### ISSUE TITLE
Backups appear to be incomplete/corrupt

### ISSUE THREAD

**Issue by Kilandor** [alcros33/MHW-Costume-Armor#10]
I attempted to restore the backup save that is made however it appears to be an incomplete copy.

The backed  up file is only 3kb
The original save files are 9kb

Upon trying to launch the game from the backup save file. The game crashes when it tries to open and load the save files.

**Comment by alcros33** [comment]
You are right, I never noticed.
It seems there was an issue with the std::filesystem::copy function.
Anyway, I made a filesystem library myself and I just tested that it copies everything properly
It will be added on next release

**Comment by Kilandor** [comment]
Just for the sake of trying it out. I did try it.

It appears to be working now. Great work
