### ISSUE TITLE
Crashing when searching for save data

### ISSUE THREAD

**Issue by AmericanEnglish** [alcros33/MHW-Costume-Armor#12]
Not sure why but it no longer works for me. It used to work just fine.  I downloaded the latest binaries.

The program starts up.
I click "Search for MHW Save Data" and then after some time it immediately crashes while doing this step. 

MHW version -> Latest
Running it through steam, and these are the only two lines in the log
```
(2019-08-02 16:44:27,94) [DEBUG] Steam UserData ID: number here
(2019-08-02 16:44:27,94) [DEBUG] Steam Game Directory: c:\program files (x86)\steam\userdata\number here\second number here\
```
Does it have any C++ distributed dependencies that aren't listed?
I can't possibly imagine why this is happening when it never has before.

**Comment by alcros33** [comment]
In fact this was my fault, I didn't updated the binaries on github, just on nexus.
Mostly because I'm just too lazy lol
Btw It doesn't have any C++ distributed dependencies, because it was compiled using MinGW compiler. (The more you know)

**Comment by alcros33** [comment]
Just update to version 0.14.2 and everything should be fine
