### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by Reooool** [alcros33/MHW-Costume-Armor#17]
Hey guys,thanks for your work firstly.After Kulve Taroth arrived in Iceburg,i find that the program not work any more.There's an error occured when i click to search MHW Character Data.May u guys repair the problem? thx

**Comment by gsabcdymm1** [comment]
My program works well after i remove my mods。U can try

**Comment by Reooool** [comment]
> 删除我的mod后，我的程序运行良好。您可以尝试

it works again,thx!
