### ISSUE TITLE
Broke with last update v15.23 (6 October 2024)

### ISSUE THREAD

**Issue by matheus-il** [alcros33/MHW-Costume-Armor#27]
This mod unfortunately no longer works with v15.23.
Can you fix it when you have time?

**Comment by alcros33** [comment]
Fixed on latest release

**Comment by TheJackOfTrades** [comment]
> Fixed on latest release

Absolutely love this mod! Thank you for sticking by it even after many other mod makers seem to have stopped updating their mods
