### ISSUE TITLE
[Enhancement] - Add option to select armor ID from drop down with armor name

### ISSUE THREAD

**Issue by jmctune** [alcros33/MHW-Costume-Armor#3]
Great mod - loving it.

Opening as an enhancement/suggestion:

For the different armor pieces where you enter the armor value, since we already know the IDs (based on the google sheets doc floating around), could a drop down be created within each armor field with the armor name and ID already pre-populated so we can just select from the list?

Thanks!

**Comment by alcros33** [comment]
Checkout solomoth's fork, he is already working on that!
He may have already finished it.
