### ISSUE TITLE
Missing "no equipment" option

### ISSUE THREAD

**Issue by wog24435** [alcros33/MHW-Costume-Armor#5]
The dropdown menu is missing the no equipment option. IDs 252 and 253 form the [spreadsheet](https://docs.google.com/spreadsheets/d/1rrDOfDw0g6jpmEMiqTNhPUwkOTsjjL8sMibTGNUa4gI/htmlview).

Options "None (255)" and "Unknown (255)" are duplicated.

**Comment by alcros33** [comment]
"Unknown" is sort of a workaround to the remotely posible case of the app reading and unknwon value from the memory it, will occupy that placeholder and "(255)" will be replaced with the unknwon value.

I don't even know if that scenario is even posible, but I didn't know how to handle it.

**Comment by alcros33** [comment]
I'll have the script only skip cells, not rows. With the exception of the king and queen beetle.
I'm pretty sure those will cause tons of crashed if left unhandled and I'm still not sure how to handle them yet.

**Comment by alcros33** [comment]
Do 252 and 253 have the same behavior ?

**Comment by wog24435** [comment]
From my tests, yes, they seem to do the same thing. I haven't tested the body, since it's marked in red, but the other parts seem to be working, more or less. As I said previously, setting the hands and legs to 252 or 253 makes them invisible, but it does not seem crash the game when changing locations.
